const ResumeApi = [
    {
        id: 1,
        category: "education",
        year: "Moringa School (2023 -2023)",
        title: "Full stack web developer",
        desc: "Taking risks in life definitely pays",
        rate: "8/10",
    },
    {
        id: 2,
        category: "education",
        year: "Africa Nazarene University (2020 - to date)",
        title: "Bachelors of procurement and supply chain management",
        desc: "My first career course",
        rate: "6/10",
    },
    {
        id: 3,
        category: "education",
        year: "Kangema High School (2016 - 2019)",
        title: "Kenya Certificate of Secondary Education",
        desc: "The best training in Kenya",
        rate: "8/10",
    },
    {
        id: 4,
        category: "education",
        year: "Gitei Primary School (2007 - 2015)",
        title: "Kenya Certificate of Primary Education",
        desc: "The most basic training in Kenya",
        rate: "9/10",
    },
    {
        id: 5,
        category: "experience",
        year: "Jimsam Fruits Palour (2020-2020)",
        title: "Overall manager",
        desc: "A good trial for my career",
        rate:  "8/10",
    },
    {
        id: 6,
        category: "experience",
        year: "Freelancer (2023 - to date)",
        title: "Freelancing for my career",
        desc: "A good trial for my career when not under supervision",
        rate: "7/10",
    },
]
export default ResumeApi