const TestimonialApi = [
    {
        id: 1,
        image: "./image/cr1.png",
        design:"NCD - DESIGN",
        name: "Italian Jim",
        officer: "Marketing Officer",
        post: "Jimmy Hub Techies",
        date: "Via Twitter - April 2, 2019 - Aug 30, 2022",
        desc: "No human is limited! Powerful words that we live with every single day. I have witnessed great things that I couldn't imagine that he could do.",
    },
    {
        id: 2,
        image: "./image/oz1.png",
        design:"Hydraulic Expert",
        name: "John Rayz",
        officer: "Head of Operations",
        post: "Silver Power",
        date: "Heave Department - Mar 3, 2017 - Dec 30, 2021",
        desc: "Ambition is always what keeps us moving. Be growth oriented is every place you find yourself and thats what Sam has proved to be.",
    },
    {
        id: 3,
        image: "./image/th1.png",
        design:"Founder",
        name: "Charlies Maestro",
        officer: "Chief Executive Officer",
        post: "Charlies Motors",
        date: "Via Twitter - Jul 7, 2018 - Sep 30, 2023",
        desc: "Discipline is a very crutial component to success, and there is no shortcut you have take the ladder. He is very disciplined in his workplace",
    },
    {
        id: 4,
        image: "./image/rj1.png",
        design:"Founder",
        name: "Jaynet Jyn",
        officer: "Chief Executive Officer",
        post: "Android app designs",
        date: "Fiver - Feb 17, 2015 - Jul 27, 2021",
        desc: "Success is for the chosen few. Those who work effortlessly but determined and focused to their goals, and so he is.",
    },
    {
        id: 5,
        image: "./image/jd1.png",
        design:"Glassfin",
        name: "Boss B",
        officer: "Director",
        post: "e-bay  design",
        date: "LinkedIn - Jan 3, 2020 - Nov 30, 2023",
        desc: "Purpose to live your life as you should. Learn how to live the moment and celebrate small wins, we have been together since school days and he lives the moment.",
    },
]
export default TestimonialApi